---
configure_cluster: true
asm_disk_management: asmlib

oracle_asm_diskgroups:
  - diskgroup: CRS
    state: present
    properties:
      - { redundancy: NORMAL, ausize: 4 }
    attributes:
      - { name: compatible.asm,   value: 12.2.0.1.0 }
      - { name: compatible.rdbms, value: 12.2.0.1.0 }
    disk:
      - { device: /dev/sdb, asmlabel: CRS01 }
      - { device: /dev/sdc, asmlabel: CRS02 }
      - { device: /dev/sdd, asmlabel: CRS03 }
  - diskgroup: DATA
    state: present
    properties:
      - { redundancy: EXTERNAL, ausize: 4 }
    attributes:
      - { name: compatible.asm,   value: 12.2.0.1.0 }
      - { name: compatible.rdbms, value: 12.2.0.1.0 }
    disk:
      - { device: /dev/sde, asmlabel: DATA01 }
  - diskgroup: FRA
    state: present
    properties:
      - { redundancy: EXTERNAL, ausize: 4 }
    attributes:
      - { name: compatible.asm,   value: 12.2.0.1.0 }
      - { name: compatible.rdbms, value: 12.2.0.1.0 }
    disk:
      - { device: /dev/sdf, asmlabel: FRA01 }

# Tipo de storage: asm ou fs
storage_type: asm
