---
# Método de gerência dos discos ASM: asmlib ou udev
# OL8/OL9 com UEK7+: asmlib v3 (sem kmod-oracleasm)
asm_disk_management: asmlib

# Configurações ASMLib
asm_disk_owner: oracle
asm_disk_group: dba
asm_disk_mode: "0660"

# udev - owner/group dos dispositivos
asm_udev_owner: oracle
asm_udev_group: dba
asm_udev_mode: "0660"

# Diretório de stage
oracle_stage: /u01/stage
oracle_user: oracle
oracle_group: oinstall
