---
galaxy_info:
  role_name: oradb-create
  description: Criacao do Oracle Database via DBCA (SI e RAC, ASM e Filesystem)
  min_ansible_version: "2.14"
  platforms:
    - name: OracleLinux
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - oracle
    - database
    - dbca

dependencies: []
