---
all:
  children:
    si:
      hosts:
        ol9-si-01:
          ansible_host: 192.168.15.180
    rac:
      hosts:
        ol8-rac-01:
          ansible_host: 192.168.15.181
        ol8-rac-02:
          ansible_host: 192.168.15.182
