---
# =============================================================================
# Inventário DEV
# =============================================================================

all:
  children:

    # ── Single Instance – Filesystem ──────────────────────────────────────────
    oracle_si_fs:
      hosts:
        dev-db-01:
          ansible_host: 10.0.10.11

    # ── Single Instance – ASM ─────────────────────────────────────────────────
    oracle_si_asm:
      hosts:
        dev-db-02:
          ansible_host: 10.0.10.12

    # ── RAC – ASM ─────────────────────────────────────────────────────────────
    oracle_rac:
      hosts:
        dev-rac-01:
          ansible_host: 10.0.20.11
          oracle_rac_node_number: 1
        dev-rac-02:
          ansible_host: 10.0.20.12
          oracle_rac_node_number: 2

    # ── Grupo geral de servidores de banco ────────────────────────────────────
    dbservers:
      children:
        oracle_si_fs:
        oracle_si_asm:
        oracle_rac: